### ISSUE TITLE
Docker Build failing

### ISSUE THREAD

**Issue by evil-dog** [ccutrer/waterfurnace_aurora#71]
I'm trying to build a docker container and it's failing. I know nothing about ruby, so am lost on how to proceed.

docker-compose.yaml:
````
services:
  waterfurnace_aurora:
    container_name: waterfurnace_aurora
    build:
      context: https://github.com/ccutrer/waterfurnace_aurora.git#main
      dockerfile: ./docker/Dockerfile
    image: ccutrer/waterfurnace_aurora

    restart: always

    devices:
      - '/dev/ttyUSB0'
    environment:
      TTY: "/dev/ttyUSB0"
      MQTT: "mqtt://mosquitto"
````

build log:
````
$ docker compose build
<fetching and extracting clipped>
=> ERROR [waterfurnace_aurora_mqtt 2/3] RUN gem install waterfurnace_aurora -v 1.4.6                            160.5s
------                                                                                                                  
 > [waterfurnace_aurora_mqtt 2/3] RUN gem install waterfurnace_aurora -v 1.4.6:                                         
99.57 Successfully installed daemons-1.4.1                                                                              
99.57 Building native extensions. This could take a while...
129.7 Successfully installed eventmachine-1.2.7
129.7 Successfully installed rack-2.2.10
129.7 Building native extensions. This could take a while...
132.7 Successfully installed thin-1.8.2
132.7 Successfully installed ruby2_keywords-0.0.5
132.7 Successfully installed mustermann-2.0.2
132.7 Successfully installed rack-protection-2.2.4
132.7 Successfully installed tilt-2.4.0
132.7 Successfully installed sinatra-2.2.4
132.7 Building native extensions. This could take a while...
157.8 ERROR:  Error installing waterfurnace_aurora:
157.8   The last version of ffi (~> 1.9, >= 1.9.3) to support your Ruby & RubyGems was 1.17.0. Try installing it with `gem install ffi -v 1.17.0` and then running the current command again
157.8   ffi requires RubyGems version >= 3.3.22. The current RubyGems version is 3.1.6. Try 'gem update --system' to update RubyGems itself.
158.4 Successfully installed digest-crc-0.6.5
158.4 Successfully installed rmodbus-ccutrer-2.1.1
158.4 Successfully installed net-telnet-rfc2217-1.0.2
158.4 Successfully installed mqtt-ccutrer-1.0.3
158.4 Successfully installed homie-mqtt-1.6.3
158.4 Successfully installed mqtt-homeassistant-0.1.6
------
failed to solve: process "/bin/sh -c gem install waterfurnace_aurora -v ${WATERFURNACE_AURORA_VERSION}" did not complete successfully: exit code: 1
````
